var product = [

    {   id:1, 
        title:'Racket1', 
        price:150, 
        rating: 3, 
        image:'img/victor1.jpg', 
        des: 'This is a white badminton racket. For advanced players looking for increased shuttle hold for explosive smashes and relentless attacking '},

    {   id:2, 
        title:'Racket2', 
        price:250, 
        rating: 4, 
        image:'img/victor2.jpg', 
        des: 'This is an orange badminton racket. For advanced players looking to dominate from the backcourt '},

    {   id:3, 
        title:'Racket3', 
        price:80, 
        rating: 4, 
        image:'img/victor3.jpg', 
        des: 'This is a blue badminton racket. For advanced players looking for accuracy, touch, and feel for skillful net play'},

    {   id:4, 
        title:'Racket4', 
        price:90, rating: 5, 
        image:'img/victor4.jpg', 
        des: 'This is a green badminton racket. The Aero box fram design combines soild hitting feel and quick swing'},

    {   id:5, 
        title:'Racket5', 
        price:100, 
        rating: 5, 
        image:'img/victor5.jpg', 
        des: 'This is a yellow badminton racket. This is a  orange badminton racket. A world-first, new dimension graphite material, Namd, greatly improves the adhesion of the graphite fibers and resin by attaching nanomaterial directly to the graphite fiber '},

    {   id:6, 
        title:'Racket6', 
        price:200, 
        rating: 3, 
        image:'img/victor6.jpg', 
        des: 'This is a light blue badminton racket. it improves the bonding strength between the carbon fibres enabling us to take racquet shaft construction to another level'},

    {   id:7, 
        title:'Shoe1',
         price:129, 
         rating: 3, 
         image:'img/man1.jpg', 
         des: 'This is a white badminton shoe for man. YC’s lightest shoe at 270g (26cm/ U.S. Size 8). Superior ventilation and solid fit'},

    {   id:8,  
        title:'Shoe2', 
        price:99, 
        rating: 4, 
        image:'img/man2.jpg', 
        des: 'This is a red badminton shoe for man. Comfortable lightweight model with Power Cushion'},

    {   id:9, 
        title:'Shoe3', 
        price:199, 
        rating: 4, 
        image:'img/man3.jpg', 
        des: 'This is a blue badminton shoe for man. New POWER CUSHION+ construction enables a new level of fast and light footwork'},

    {   id:10, 
        title:'Shoe4', 
        price:88, 
        rating: 3, 
        image:'img/woman1.jpg', 
        des: 'This is a pink badminton shoe for woman. Newly designed upper provides remarkably improved fit and stability'},

    {   id:11, 
        title:'Shoe5', 
        price:55, 
        rating: 5, 
        image:'img/woman2.jpg', 
        des: 'This is a orange badminton shoe for woman. Provides a comfortable fit by tightening the laces from toe to ankle uniformly'},

    {   id:12, 
        title:'Shoe6', 
        price:69,
        rating: 2, 
        image:'img/woman3.jpg',
        des: 'This is a light blue badminton shoe for woman. Provides cushioning plus performance, so you can play your best game longer'},
]